version: '3.8'

services:
  app: 
    container_name: ds-plat
    image: ds-plat
    build: .
    volumes:
      - ./src:/app/sr—Å
      - '/app/node_modules'
    ports:
      - 80:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
