version: '3.8'

services:
  app: 
    container_name: designers-platform
    image: designers-platform
    build: 
      context: .
      target: development
    volumes:
      - ./src:/app/sr—Å
    ports:
      - 80:3000
